week4 hw finish
Lidemy/mentor-program-5th-Lindsay0214 pull request #3
Opened 2021-05-08 15:07 UTC by Lindsay0214

來惹ＱＱ 上週的繼續努力生

2021-05-12 14:06 UTC, cwc329 requested changes
作業有達到基本要求，
不錯。

不過看起來你的 eslint 好像沒有設定好，
程式碼的排版也很凌亂。
請在本地設定好 eslint，
如果不知道怎麼設定，
請回去重看 week3 的影片以及完成作業。

還有，
交作業前請看自我檢討並且依照檢討訂正作業，
之後如果出現太多自我檢討就有提過的錯誤，
可能就不會批改那次的作業。

2021-05-12 14:06 UTC, cwc329 commented on homeworks/week4/hw1.js
> +// });
不用的程式碼，以刪除取代註解。

2021-05-12 14:06 UTC, cwc329 commented on homeworks/week4/hw1.js
> +        console.log(`${data[i].id} ${data[i].name}`);
縮排問題，請檢查排版。

2021-05-12 14:06 UTC, cwc329 commented on homeworks/week4/hw1.js
> +console.log(process.argv)
為何要 log 這個？

2021-05-12 14:06 UTC, cwc329 commented on homeworks/week4/hw2.js
> +            newName
這是 shorthand，object 的 key 會變成變數名稱。
你這樣會更新不成功。

2021-05-12 14:06 UTC, cwc329 commented on homeworks/week4/hw2.js
> +        if (err) {
要檢查 status code。
這是自我檢討的部分，交作業前請先看過自我檢討並且訂正。

2021-05-12 14:06 UTC, cwc329 commented on homeworks/week4/hw5.md
> +request(`${BASE_URL}`, (err, res, body) => {
有示範 code 不錯。
不過 api 會回傳什麼呢？

2021-05-12 14:06 UTC, cwc329 commented on homeworks/week4/hw5.md
> +request(`${BASE_URL}`, (err, res, body) => {
另外如果是文件建議直接用網址而非用變數形式，
這樣會比較好閱讀。

而且你這邊 `BASE_URL` 和你上面所寫的 api url 不同，
這樣應該是不會拿到需要的資訊的。

2021-05-12 14:06 UTC, cwc329 commented on homeworks/week4/hw5.md
> +name,
雖然是 markdown，
程式碼還是排版一下。

2021-05-25 10:39 UTC, merged

2021-05-25 11:11 UTC, ClayGao commented
這邊的作業訂正完之後，如果要請助教批改，再麻煩另開新分支 "week4 訂正"，並依照一般交作業流程，或者發 PR 後指定助教看都 ok，謝謝同學